name: Create release from PR info

on:
  push:
    branches: [ main ]

jobs:
  get-pr-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-pr-info.outputs.VERSION }}
      pr_num: ${{ steps.get-pr-info.outputs.PR_NUM }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
          ref: 'main'
      - name: Obtain PR and container tag info
        id: get-pr-info
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep "version=" setup.py  | awk -F "=" '{print $2}' | tr -d "',")
          git --no-pager log --pretty=oneline
          PR_NUM=$(git --no-pager log --pretty=oneline  | grep "#" | head -n 1  | awk -F '#' '{print $2}' | awk '{print $1}' | tr -d '(#)')
          echo "VERSION $VERSION"
          echo "PR_NUM $PR_NUM"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "PR_NUM=$PR_NUM" >> $GITHUB_OUTPUT

  create-github-release:
    runs-on: ubuntu-latest
    needs: get-pr-info
    steps:
      - name: Create release in Github
        id: create-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{needs.get-pr-info.outputs.version}}
          PR_NUM: ${{needs.get-pr-info.outputs.pr_num}}
        run: |
          gh pr view $PR_NUM --json body --repo ${{ github.repository }} | jq -r .body > changelog.md
          gh release create ${VERSION} -F changelog.md --repo ${{ github.repository }}